### ISSUE TITLE
View Source PDF on full page.

### ISSUE THREAD

**Issue by Cas-B** [jessetilro/research#21]
It would be nice to see the PDF on full page.

**Comment by jessetilro** [comment]
Does opening a new tab with the PDF count as displaying the PDF in full screen (as added by #66), or should it be in the same tab in the form of some pop-up?

**Comment by FlorisXll** [comment]
@jessetilro The function introduced in #66 is already really good. However, if you would really like to enhance it, I would say that that clicking the 'full screen' button would make the pdf full screen in the same tab while still keeping the main header/navigation bar so + a button to revert full screen.

**Comment by Cas-B** [comment]
@jessetilro Would say that opening a new tab with the PDF in full screen also counts as seeing the PDF on full page:)

**Comment by FlorisXll** [comment]
This one seems fixed now.
