### ISSUE TITLE
Add the ability to add PDF on Source import.

### ISSUE THREAD

**Issue by FlorisXll** [jessetilro/research#65]
Instead of importing and then going to 'Edit' it would be nice to add the PDF together with the BibTex information.

**Comment by jessetilro** [comment]
Nice one. Keep in mind that the import allows you to specify an arbitrary amount of bibtex items. I think it would be fine if we associate the PDF with the first item.

**Comment by jessetilro** [comment]
There is now the so called "Dropzone" page where you can include either a local PDF file or a URL to a publicly available PDF file along with the Bibtex / reference / title in order to add a new source.
