### ISSUE TITLE
Allow users to register

### ISSUE THREAD

**Issue by jessetilro** [jessetilro/research#70]

**Comment by jessetilro** [comment]
To allow for this functionality the mailer should be set up first, otherwise the registration confirmation link cannot be sent. Enabling user registration functionality is quite straightforward since it just requires the Devise gem to be configured a bit further. Will update this issue when the mailerhas been taken care of.

**Comment by Cas-B** [comment]
Thank you:)

**Comment by jessetilro** [comment]
Users can now register an account. They will receive a confirmation email with a link to confirm their email address and activate their account. After signing in for the first time, they will be prompted to create their first project.
