### ISSUE TITLE
DOI should not be a number, but plain text

### ISSUE THREAD

**Issue by mpsijm** [jessetilro/research#75]
Example DOI (digital object identifier): [`10.1109/SANER.2016.108`](https://doi.org/10.1109/SANER.2016.108)
The tool expects a number as input but in most cases the DOI contains at least a slash `/` and some periods `.`, and in this case also letters.

**Comment by jessetilro** [comment]
Fixed, thanks! The DOI is now also verified using a regex (soft validation, just shows warning) and the URL is automatically generated (doi.org) if DOI is present and no custom URL is specified yet.
